<?php
// Generated by ZF2's ./bin/classmap_generator.php @ Sun, 15 Jan 2012 19:46:42 -0700
return array(
    'PlaygroundUser\Module'                            => __DIR__ . '/Module.php',
    'PlaygroundUser\Event\ResolveTargetEntityListener' => __DIR__ . '/src/PlaygroundUser/Event/ResolveTargetEntityListener.php',
    'PlaygroundUser\Mapper\UserMetaDoctrine'           => __DIR__ . '/src/PlaygroundUser/Mapper/UserMetaDoctrine.php',
    'PlaygroundUser\Mapper\UserDoctrine'               => __DIR__ . '/src/PlaygroundUser/Mapper/UserDoctrine.php',
    'PlaygroundUser\Entity\UserMappedSuperClass'       => __DIR__ . '/src/PlaygroundUser/Entity/UserMappedSuperClass.php',
    'PlaygroundUser\Entity\UserMetaMappedSuperClass'   => __DIR__ . '/src/PlaygroundUser/Entity/UserMetaMappedSuperClass.php',
    'PlaygroundUser\Entity\UserMeta'                   => __DIR__ . '/src/PlaygroundUser/Entity/UserMeta.php',
    'PlaygroundUser\Entity\User'                       => __DIR__ . '/src/PlaygroundUser/Entity/User.php',
);
