<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounduser');// Pour le texte ?>
<?php
$form = $this->editUserForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/playgrounduser/edit', array('userId' => $this->userId)));
$form->setAttribute('method', 'post');
?>

<h1>Edit user</h1>

<?php echo $this->form()->openTag($form) ?>
<?php echo $this->formButton($form->get('submit')) ?>

<?php if ($this->redirect): ?><input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" /><?php endif ?>

<div id="content" class="tabbable tabs-left">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <li class="active"><a href="#identity" data-toggle="tab"><?php echo $this->translate('identity'); ?></a></li>
        <li><a href="#address" data-toggle="tab"><?php echo $this->translate('Address'); ?></a></li>
        <li><a href="#avatar" data-toggle="tab"><?php echo $this->translate('Avatar'); ?></a></li>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <div class="tab-pane active" id="identity">
            <div>
                <?php foreach ($form as $element): ?>
                    <?php if ($element->getLabel() != null): ?>
                        <?php echo $this->formLabel($element) ?>
                    <?php endif ?>
                    <?php if ($element instanceof Zend\Form\Element\Button): ?>
                    <?php elseif ($element instanceof Zend\Form\Element\Select): ?>
                    <?php echo $this->formSelect($element) . $this->formElementErrors($element) ?>
                    <?php elseif ($element instanceof Zend\Form\Element\Radio): ?>
                    <?php echo $this->formRadio($element) . $this->formElementErrors($element) ?>
                    <?php elseif ($element instanceof Zend\Form\Element\File): ?>
                    <?php else: ?>
                    <?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
                    <?php endif ?>
                <?php endforeach ?>
            </div>
        </div>
        <div class="tab-pane" id="address">
            <div>BLBLBLBLLBLBL</div>
        </div>
        <div class="tab-pane" id="avatar">
            <div><?php echo $this->formFile($form->get('avatar')); ?></div>
            <?php if($form->get('avatar')->getValue() != ''):?>
            	<img src="<?php echo $this->basePath($form->get('avatar')->getValue()); ?>" />
            <?php endif;?>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $('#tabs').tab();
        $('.date').datepicker();
    });
</script>