<div id="lost-pass" class="row-fluid">
	<div class="container-content span8">
		<div class="row-fluid">
		
			<p class="h2">Votre mot de passe a été modifié.</p>
		
			<div id="container-form" class="row-fluid">				
				<p>Vous pouvez maintenant vous connecter en utilisant votre nouveau mot de passe.</p>
				<p class="change-password-link"><a href="<?php echo $this->url('frontend/zfcuser/login') ?>">> Se connecter</a></p>
			</div>
			
		</div>
	</div>
</div>