<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounduser');// Pour le texte ?>
<!-- NEW USER -->
<div id="new-user" class="row-fluid">
	<div class="span8 center">
		<div class="row-fluid">
			<p class="h2"><?php echo $this->translate('login or register'); ?></p>

			<!-- login -->
			<div id="login-part" class="backgrey row-fluid" data-redirect="<?php  if($this->redirect) : echo $this->redirect; else : $this->url('frontend'); endif; ?>">
				<div class="row-fluid hand-arrow-double">
					<div class="block-left span7">
						<p class="green"><?php echo $this->translate('Already an account ?')?></p>
					</div>
					<div class="block-right span5">
					<?php if(!$this->zfcUserIdentity()): ?>
					    <?php echo $this->playgroundUserLoginWidget(array(
			    		        'redirect' => ($this->redirect) ? $this->redirect : $this->url('frontend'),
			    		        'enableRegistration' => false,
			    		        'template' => 'playground-user/register/login.phtml'
				    		)); ?>
					<?php endif;?>
					<div class="input-login-error"></div>
					</div>
				</div>
			</div>

			<?php
		    if (!$this->enableRegistration) {
		        print "Registration is disabled";
		        return;
		    }
		    $form = $this->registerForm;
		    $form->prepare();
		    $form->setAttribute('method', 'post');
			$form->setAttribute('class', 'validate');
		    ?>

			<!-- create account -->
			<div id="register-form" class="backgrey row-fluid">
				<div class="row-fluid hand-arrow-simple">
					<div class="span5">
						<p class="green"><?php echo $this->translate('Create an account')?></p>
					</div>
					<div id="fb-connect" class="span7">
						<p class="fb-connect-label"><?php echo $this->translate('Use Facebook connect')?></p>
						<p><a href="<?php echo $this->url('frontend/zfcuser/register',array('socialnetwork' => 'facebook')) . ($this->redirect ? '?redirect='.$this->redirect : '');?>"><img src="<?php echo $this->frontendAssetPath('images/common/fb-connect.png') ?>" alt="Facebook Connect" /></a></p>
					</div>
				</div>

				<!-- start form -->
		        <?php echo $this->form()->openTag($form) ?>
					<div class="row-fluid">
						<div class="block-left yourtitle span4"><?php echo $form->get('title')->getLabel(); ?> <span>*</span> :</div>
						<div class="block-right civility span7">
							<?php echo $this->formRadio($form->get('title')) . $this->formElementErrors($form->get('title')) ?>
						</div>
					</div>
					<div class="row-fluid">
						<div class="block-left span4"><?php echo $form->get('lastname')->getLabel(); ?> <span>*</span> :</div>
						<div class="block-right span7">
							<?php echo $this->formInput($form->get('lastname')) ?>
							<?php echo $this->formElementErrors($form->get('lastname')) ?>
                            <img src="<?php echo $this->frontendAssetPath('images/common/form-no.png') ?>" class="form-no">
						</div>
					</div>
					<div class="row-fluid">
						<div class="block-left span4"><?php echo $form->get('firstname')->getLabel(); ?> <span>*</span> :</div>
						<div class="block-right span7">
							<?php echo $this->formInput($form->get('firstname')) ?>
							<?php echo $this->formElementErrors($form->get('firstname')) ?>
                            <img src="<?php echo $this->frontendAssetPath('images/common/form-no.png') ?>" class="form-no">
						</div>
					</div>
					<!-- div class="row-fluid">
						<div class="block-left span6">
							<?php //echo $this->formLabel($form->get('username')) ?><span>*</span> :
						</div>
						<div class="block-right span6">
						    <?php //echo $this->formInput($form->get('username')) ?>
						</div>
					</div-->
					<div class="row-fluid">
						<div class="block-left span4"><?php echo $form->get('email')->getLabel(); ?> <span>*</span> :</div>
						<div class="block-right span7">
						    <?php echo $this->formInput($form->get('email')) ?>
						    <?php echo $this->formElementErrors($form->get('email')) ?>
                            <img src="<?php echo $this->frontendAssetPath('images/common/form-no.png') ?>" class="form-no">
						</div>
					</div>
					<?php //I do hide these fields on Facebook registration ?>
					<?php if($form->has('password')):?>
					<div class="row-fluid">
						<div class="block-left span4"><?php echo $form->get('password')->getLabel(); ?> <span>*</span> :<br/>
							<span class="annotation">6 caractères minimum</span>
						</div>
						<div class="block-right span7">
							<?php echo $this->formInput($form->get('password')) ?>
							<?php echo $this->formElementErrors($form->get('password')) ?>
                            <img src="<?php echo $this->frontendAssetPath('images/common/form-no.png') ?>" class="form-no">
						</div>
					</div>
					<div class="row-fluid">
						<div class="block-left span4"><?php echo $form->get('passwordVerify')->getLabel(); ?> <span>*</span> :</div>
						<div class="block-right span7">
							<?php echo $this->formInput($form->get('passwordVerify')) ?>
							<?php echo $this->formElementErrors($form->get('passwordVerify')) ?>
                            <img src="<?php echo $this->frontendAssetPath('images/common/form-no.png') ?>" class="form-no">
						</div>
					</div>
					<?php endif;?>
					<div class="row-fluid">
						<div class="block-left span4"><?php echo $form->get('dob')->getLabel(); ?><span>*</span> :</div>
						<div class="block-right span7 register-select mobile">
							<?php echo $this->formDateTime($form->get('dob')) ?>
							<?php echo $this->formElementErrors($form->get('dob')) ?>
                            <img src="<?php echo $this->frontendAssetPath('images/common/form-no.png') ?>" class="form-no form-no-select">
						</div>
					</div>
					<div class="row-fluid">
						<div class="block-left span4"><?php echo $form->get('postal_code')->getLabel(); ?> <span>*</span> :</div>
						<div id="wrapcp" class="block-right span7">
							<?php echo $this->formInput($form->get('postal_code')) ?>
							<?php echo $this->formElementErrors($form->get('postal_code')) ?>
                            <img src="<?php echo $this->frontendAssetPath('images/common/form-no.png') ?>" class="form-no form-no-cp">
						</div>
					</div>

					<!-- opt-in -->
					<div class="row-fluid opt-in">
						<b><?php echo $this->translate('Inscrivez-vous aux newsletters :')?></b>
						<div class="span9 raz">
							<p><?php echo $this->translate('Je souhaite recevoir la newsletter de Playground')?> <span>*</span><br/>
							<?php echo $this->translate('(nouveaux jeux-concours, bons plans, invitations VIP...)')?></p>
						</div>
						<div class="span3">
							<?php echo $this->formRadio($form->get('optin')) ?>
							<?php echo $this->formElementErrors($form->get('optin')) ?>
						</div>
					</div>

					<div class="row-fluid opt-in">
						<div class="span9">
							<p><?php echo $this->translate('Je souhaite recevoir les offres des partenaires de Playground')?> <span>*</span><br/>
							<?php echo $this->translate('(réductions, bons plans...)')?></p>
						</div>
						<div class="span3">
							<?php echo $this->formRadio($form->get('optinPartner')) ?>
							<?php echo $this->formElementErrors($form->get('optinPartner')) ?>
						</div>
					</div>
					<div id="btn-create-account" class="row-fluid">
						<div class="span7 center">
							<?php echo $this->formButton($form->get('submit')) ?>
						</div>
					</div>
					<?php if ($this->redirect): ?>
		                <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
		            <?php endif ?>
		        <?php echo $this->form()->closeTag() ?>
				<!-- end form -->

			</div>
			<p id="annotation"><?php echo $this->translate('* champs obligatoires')?></p>

		</div>
	</div>
</div>
<!-- END NEW USER -->