<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounduser');// Pour le texte ?>
<!-- NEW USER -->
<div id="new-user" class="row-fluid">
	<div class="span8 center">
		<div class="row-fluid">
			<p class="h2">Un mail vous à été envoyé à l'adresse <?php echo $this->escapeHtml($this->userEmail); ?>, cliquez sur le lien de confirmation qu'il contient pour valider votre inscription.</p>
		</div>
	</div>
</div>