<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounduser');// Pour le texte ?>
<!-- USER MODIFY -->
<div id="account-modify" class="row-fluid">
	<?php if ($statusPassword === true) : ?>
    <div class="alert alert-success"><?php echo $this->translate('Password changed successfully.') ?></div>
    <?php elseif ($statusPassword === false) : ?>
    <div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.') ?></div>
    <?php endif; ?>
    <?php if ($statusEmail === true) : ?>
    <div class="alert alert-success"><?php echo $this->translate('Email address changed successfully.') ?></div>
    <?php elseif ($statusEmail === false) : ?>
    <div class="alert alert-error"><?php echo $this->translate('Unable to update your email address. Please try again.') ?></div>
    <?php endif; ?>
    <?php if ($statusInfo === true) : ?>
    <div class="alert alert-success"><?php echo $this->translate('Info changed successfully.') ?></div>
    <?php elseif ($statusInfo === false) : ?>
    <div class="alert alert-error"><?php echo $this->translate('Unable to update your info. Please try again.') ?></div>
    <?php endif; ?>

	<!-- content -->
	<p class="h1">Modifier mes informations</p>
	<!-- update login -->
	<div id="update-login" class="row-fluid backgrey">
		<div class="update-login-block">
			<p class="green-hand-star">Modifier mes identifiants</p>
			<p class="silver">Vos identifiants vous permettent de vous connecter à votre compte Playground.</p>
		    <?php

            $formEmail = $this->changeEmailForm;

            $formEmail->prepare();
            $formEmail->setAttribute('action', $this->url('zfcuser/profile'));
            $formEmail->setAttribute('method', 'post');

            ?>
            <?php echo $this->form()->openTag($formEmail) ?>
		    <?php echo $this->formInput($formEmail->get('identity')) ?>
			<?php echo $this->formElementErrors($formEmail->get('identity')) ?>

			<div class="row-fluid">
				<div class="span4">
					<p><?php echo $formEmail->get('newIdentity')->getLabel(); ?> :</p>
				</div>
				<div class="span6">
					<?php echo $this->formInput($formEmail->get('newIdentity')) ?>
					<?php echo $this->formElementErrors($formEmail->get('newIdentity')) ?>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span4">
					<p><?php echo $formEmail->get('newIdentityVerify')->getLabel(); ?> :</p>
				</div>
				<div class="span6">
					<?php echo $this->formInput($formEmail->get('newIdentityVerify')) ?>
					<?php echo $this->formElementErrors($formEmail->get('newIdentityVerify')) ?>
				</div>
			</div>

			<div class="row-fluid">
				<div class="span4">
					<p><?php echo $formEmail->get('credential')->getLabel(); ?> :</p>
				</div>
				<div class="span6">
					<?php echo $this->formInput($formEmail->get('credential')) ?>
					<?php echo $this->formElementErrors($formEmail->get('credential')) ?>
				</div>
			</div>
			<input type="submit" class="btn btn-success" value="Valider"/>
			<?php echo $this->form()->closeTag() ?>
		</div>

		<div class="update-login-block">
			<?php

            $form = $this->changePasswordForm;

            $form->prepare();
            $form->setAttribute('action', $this->url('zfcuser/profile'));
            $form->setAttribute('method', 'post');
			$form->setAttribute('class', 'validate');

            $emailElement = $form->get('identity');
            $emailElement->setValue($this->zfcUserIdentity()->getEmail());

            echo $this->form()->openTag($form);

            ?>
            <?php echo $this->formElementErrors($form->get('identity')); ?>
            <?php echo $this->formInput($form->get('identity')); ?>
			<p class="green-hand-star">Changer le mot de passe</p>

			<div class="row-fluid">
				<div class="span4">
					<p><?php echo $form->get('credential')->getLabel(); ?> :</p>
				</div>
				<div class="span6">
					<?php echo $this->formInput($form->get('credential')) ?>
					<?php echo $this->formElementErrors($form->get('credential')) ?>
				</div>
			</div>

			<div class="row-fluid">
				<div class="span4">
					<p><?php echo $form->get('newCredential')->getLabel(); ?> :<br/>
						<span class="annotation">6 caractères minimum</span></p>
				</div>
				<div class="span6">
					<?php echo $this->formInput($form->get('newCredential')) ?>
					<?php echo $this->formElementErrors($form->get('newCredential')) ?>
				</div>
			</div>

			<div class="row-fluid">
				<div class="span4">
					<p><?php echo $form->get('newCredentialVerify')->getLabel(); ?> :</p>
				</div>
				<div class="span6">
					<?php echo $this->formInput($form->get('newCredentialVerify')) ?>
					<?php echo $this->formElementErrors($form->get('newCredentialVerify')) ?>
				</div>
			</div>

			<?php //echo $this->formInput($form->get('submit')); ?>
			<input type="submit" class="btn btn-success" value="Valider"/>
			
			<?php echo $this->form()->closeTag() ?>
		</div>

	</div>

	<!-- update adresse -->
	<!-- start form change adresse -->

	<?php
    $formInfo = $this->changeInfoForm;

    $formInfo->prepare();
    $formInfo->setAttribute('action', $this->url('zfcuser/profile'));
    $formInfo->setAttribute('method', 'post');
	$formInfo->setAttribute('class', 'validate');

    ?>
    <?php echo $this->form()->openTag($formInfo) ?>
    <?php echo $this->formHidden($formInfo->get('email')); ?>
		<div id="update-adresse" class="row-fluid backgrey">
			<p class="green-hand-star">Modifier mes coordonées</p>
			<p class="orange"><b id="motto-gagner-points-coordonnees">Validez ou renseignez vos infos et gagnez des points !</b></p>

			<div class="row-fluid">
				<div class="span4">
					<p>Votre pseudonyme :</p>
				</div>
				<div class="span6">
					<?php echo $this->formInput($formInfo->get('username')); ?>
				</div>
				<div class="span2">
					<p class="orange-points"><?php echo $this->usernamePoint; ?></p>
				</div>
			</div>
			
			<div class="row-fluid">
				<div class="span4">
					<p><?php echo $formInfo->get('avatar')->getLabel(); ?> : </p>
				</div>
				<div class="span6" id="avatarfile" data-profilfile="Votre photo de profil">
					<?php echo $this->formFile($formInfo->get('avatar')); ?>
					<?php echo $this->formElementErrors($formInfo->get('avatar')) ?>
				</div>
				<div class="span2">
					<p class="orange-points">+ 150 pts</p>
				</div>
			</div>

			<div class="row-fluid civility">
				<div class="span4"><p><?php echo $formInfo->get('title')->getLabel(); ?><span class="red">*</span> :</p></div>
				<div class="span6"><?php echo $this->formRadio($formInfo->get('title')) . $this->formElementErrors($formInfo->get('title')) ?></div>
			</div>

			<div class="row-fluid">
				<div class="span4"><p><?php echo $formInfo->get('lastname')->getLabel(); ?><span class="red">*</span> :</p></div>
				<div class="span6">
					<?php echo $this->formInput($formInfo->get('lastname')) ?>
					<?php echo $this->formElementErrors($formInfo->get('lastname')) ?>
				</div>
				<div class="span2">
					<p class="orange-points">+ 25 pts</p>
				</div>
			</div>

			<div class="row-fluid">
				<div class="span4"><p><?php echo $formInfo->get('firstname')->getLabel(); ?><span class="red">*</span> :</p></div>
				<div class="span6">
					<?php echo $this->formInput($formInfo->get('firstname')) ?>
					<?php echo $this->formElementErrors($formInfo->get('firstname')) ?>
				</div>
				<div class="span2">
					<p class="orange-points">+ 25 pts</p>
				</div>
			</div>

			<div class="row-fluid">
				<div class="span4"><p><?php echo $formInfo->get('address')->getLabel(); ?> :</p></div>
				<div class="span6">
					<?php echo $this->formInput($formInfo->get('address')) ?>
					<?php echo $this->formElementErrors($formInfo->get('address')) ?>
				</div>
				<div class="span2">
					<p class="orange-points">+ 150 pts</p>
				</div>
			</div>

			<div class="row-fluid">
				<div class="span4">
					<p><?php echo $formInfo->get('address2')->getLabel(); ?> :</p>
				</div>
				<div class="span6">
					<?php echo $this->formInput($formInfo->get('address2')) ?>
					<?php echo $this->formElementErrors($formInfo->get('address2')) ?>
				</div>
			</div>

			<div class="row-fluid">
				<div class="span4 zipcode">
					<p><?php echo $formInfo->get('postal_code')->getLabel(); ?><span class="red">*</span> :</p>
				</div>
				<div class="span6">
					<?php echo $this->formInput($formInfo->get('postal_code')) ?>
					<?php echo $this->formElementErrors($formInfo->get('postal_code')) ?>
				</div>
				<div class="span2">
					<p class="orange-points">+ 25 pts</p>
				</div>
			</div>

			<div class="row-fluid">
				<div class="span4">
					<p><?php echo $formInfo->get('city')->getLabel(); ?> :</p>
				</div>
				<div class="span6">
					<?php echo $this->formInput($formInfo->get('city')) ?>
					<?php echo $this->formElementErrors($formInfo->get('city')) ?>
				</div>
				<div class="span2">
					<p class="orange-points">+ 75 pts</p>
				</div>
			</div>
			
			<div class="row-fluid">
				<div class="span4">
					<p><?php echo $formInfo->get('country')->getLabel(); ?> :</p>
				</div>
				<div class="span6">
					<?php echo $this->formSelect($formInfo->get('country')) ?>
					<?php echo $this->formElementErrors($formInfo->get('country')) ?>
				</div>
				<div class="span2">
					<p class="orange-points">+ 0 pts</p>
				</div>
			</div>

			<div class="row-fluid">
				<div class="span4">
					<p><?php echo $formInfo->get('telephone')->getLabel(); ?> :</p>
				</div>
				<div class="span6 phone">
					<?php echo $this->formInput($formInfo->get('telephone')) ?>
					<?php echo $this->formElementErrors($formInfo->get('telephone')) ?>
				</div>
				<div class="span2">
					<p class="orange-points">+ 150 pts</p>
				</div>
			</div>
			
			<div class="row-fluid">
				<div class="span4">
					<p><?php echo $formInfo->get('dob')->getLabel(); ?><span class="red">*</span> :</p></div>
				<div class="span6">
					<?php echo $this->formDateTime($formInfo->get('dob')) ?>
					<?php echo $this->formElementErrors($formInfo->get('dob')) ?>
				</div>
			</div>
			<?php //echo $this->formInput($formInfo->get('submit')); ?>
			<input type="submit" class="btn btn-success" value="Valider"/>
		</div>
	<?php echo $this->form()->closeTag() ?>
	<!-- end form change adresse-->


	<?php
    $formPrize = $this->prizeCategoryForm;
    $formPrize->setAttribute('action', $this->url('zfcuser/profile_prizes'));
    $formPrize->setAttribute('method', 'post');
    //$formInfo->prepare();
    ?>
    <?php // I check if there are some categories to select. If no... Forget the form?>
    <?php if(($formPrize->get('prizeCategory') instanceof Zend\Form\Element\MultiCheckbox )):?>
        <?php echo $this->form()->openTag($formPrize) ?>
    	<!-- update hobby-->
    	<div id="update-hobby" class="row-fluid backgrey">
    		<p class="green-hand-star">Centres d'intérêts</p>
    		<p class="orange"><b id="motto-gagner-points-hobby">Indiquez vos centres d'intérêts et gagnez 100 points !</b></p>
    		<div class="row-fluid hobbies">
                <?php echo $this->formHidden($formPrize->get('user')); ?>
                <?php echo $this->formMultiCheckbox($formPrize->get('prizeCategory')); ?>
    		</div>
    		<input type="submit" class="btn btn-success" value="Valider"/>
    	</div>
        <?php echo $this->form()->closeTag($formPrize) ?>
    <?php endif;?>

    <?php
        $formBlockAccount = $this->blockAccountForm;
        $formBlockAccount->setAttribute('action', $this->url('zfcuser/blockaccount'));
        $formBlockAccount->setAttribute('method', 'post');
        $emailElement = $formBlockAccount->get('identity');
        $emailElement->setValue($this->zfcUserIdentity()->getEmail());
        //$formInfo->prepare();
    ?>
    <!-- delete account-->
	<div id="delete-account" class="row-fluid backgrey">
	    <?php if($this->zfcUserIdentity()->getState() == 2):?>

    		<p class="green-hand-star">Réactiver mon compte</p>
    		<p>Pour réactiver votre compte : </p>
    		<p>
    			1/ Cliquez sur le bouton réactiver mon compte<br/>
    			2/ Validez votre choix<br/>
    		</p>
		<?php else:?>
    		<p class="green-hand-star">Supprimer mon compte</p>
    		<p>Pour supprimer votre compte : </p>
    		<p>
    			1/ Cliquez sur le bouton supprimer mon compte<br/>
    			2/ Validez votre choix<br/>
    			3/ Vous avez une semaine pour changer d'avis, en vous connectant tout simplement à votre compte. au delà de ce délai votre compte sera définitivement supprimé.
    		</p>
		
		<?php endif;?>
		
        <?php echo $this->form()->openTag($formBlockAccount) ?>
        <?php echo $this->formElementErrors($formBlockAccount->get('identity')); ?>
        <?php echo $this->formHidden($formBlockAccount->get('activate')); ?>
        <?php echo $this->formInput($formBlockAccount->get('identity')); ?>

		<div class="row-fluid">
			<div class="span4">
				<p><?php echo $form->get('credential')->getLabel(); ?> :</p>
			</div>
			<div class="span6">
				<?php echo $this->formInput($formBlockAccount->get('credential')) ?>
				<?php echo $this->formElementErrors($formBlockAccount->get('credential')) ?>
			</div>
		</div>
		<?php echo $this->formInput($formBlockAccount->get('submit')) ?>
		<?php echo $this->formInput($formBlockAccount->get('cancel')) ?>
		<?php echo $this->formInput($formBlockAccount->get('confirm_submit')) ?>
	
		<?php echo $this->form()->closeTag($formBlockAccount) ?>
	</div>
</div>
<!-- END USER MODIFY -->