<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 4.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title></title>
</head>
<body>
<table width="100%" cellpadding="0" cellspacing="5" border="0" bgcolor="#F3F3F3">
	<tr>
		<td align="center">
			<table width="516" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td height="589" align="left">
							<table width="516" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
								<tr height="589">
									<td height="589" width="18" style="font-size:0" valign="top">
										<img border="0" src="<?php echo $this->url('frontend', array(), array('force_canonical' => true)). 'images/content/email/email1.jpg';?>" alt="" height="589" width="18"/>
									</td>
									<td height="589" width="480" style="font-size:0">
										<table width="480" cellpadding="0" cellspacing="0" border="0">
											<tr height="102">
												<td height="102" width="480" valign="top">
													<table width="480" cellpadding="0" cellspacing="0" border="0">
														<tr height="102">
															<td height="102" width="417" style="font-size:0"><img border="0" src="<?php echo $this->url('frontend', array(), array('force_canonical' => true)). 'images/content/email/email3.jpg' ;?>" alt="" height="102" width="417"/></td>
															<td height="102" width="63" style="font-size:0"><a href="http://facebook.com/playground/"><img border="0" src="<?php echo $this->url('frontend', array(), array('force_canonical' => true)). 'images/content/email/email4.jpg';?>" alt="" height="102" width="63"/></a></td>
														</tr>
													</table>
												</td>
											</tr>
											<tr height="487">
												<td height="487" width="480" style="font-size:0">
													<table width="480" cellpadding="0" cellspacing="0" border="0">
														<td height="487" width="15" style="font-size:0"><img border="0" src="<?php echo $this->url('frontend', array(), array('force_canonical' => true)). 'images/content/email/email5.jpg';?>" alt="" height="487" width="15"/></td>
														<td height="487" width="450">
															<table width="450" cellpadding="0" cellspacing="0" border="0">
																<tr height="487">
																	<td height="487" width="450">
																		<table width="450" cellpadding="0" cellspacing="0" border="0">
																			<tr height="32">
																				<td height="32" width="450" style="font-size:18px;">
																					<font face="Arial" color="#FFFFFF" style="background-color:#8DC63F;padding-left:5px;padding-top:5px;padding-bottom:5px;padding-right:5px;">Bonjour <?php echo $this->userFirstName ?>,</font>
																				</td>
																			</tr>
																			<tr height="96">
																				<td height="96" width="450" style="font-size:14px;">
																					<font face="Arial" color="#565656">Vous vous &ecirc;tes inscrit(e) à <b>Playground</b> et nous vous en remercions.<br/><br/>Finaliser d&egrave;s &agrave; pr&eacute;sent votre inscription et tenter de gagner plein de cadeaux!</font>
																				</td>
																			</tr>
																			<tr height="77">
																				<td height="77" width="450" style="font-size:22px;" align="center">
																					<a href="<?php echo $this->serverUrl($this->url('frontend/zfcuser/verification').'?token=' .$this->record->getRequestKey()); ?>" style="text-decoration:none;"><font face="Arial" color="#FFFFFF" style="background-color:#F0AB25;padding-left:15px;padding-top:10px;padding-bottom:10px;padding-right:15px;"><b>	&gt; Valider l'inscription</b></font></a>
																				</td>
																			</tr>
																			<tr height="21">
																				<td height="21" width="450">
																					<img border="0" src="<?php echo $this->url('frontend', array(), array('force_canonical' => true)). 'images/content/email/email6.jpg';?>" alt="" height="21" width="450"/>
																				</td>
																			</tr>
																			<tr height="70">
																				<td height="70" width="450" style="font-size:12px;background-color:#f3f3f3;padding-left:20px;padding-top:10px;padding-bottom:10px;padding-right:20px;" align="center">
																					<font face="Arial" color="#272727">Si ce lien ne s'affiche pas correctement, <br/>copiez-collez cette URL dans votre navigateur :<br/><?php echo $this->serverUrl($this->url('frontend/zfcuser/verification').'?token=' .$this->record->getRequestKey()); ?></font>
																				</td>
																			</tr>
																			<tr height="62">
																				<td height="62" width="450" style="font-size:0">
																					<img border="0" src="<?php echo $this->url('frontend', array(), array('force_canonical' => true)). 'images/content/email/email7.jpg';?>" alt="" height="62" width="450"/>
																				</td>
																			</tr>
																			<tr height="70">
																				<td height="70" width="450" style="font-size:14px;" align="center">
																					<font face="Arial" color="#565656"><b>Merci et &agrave; tr&egrave;s vite sur Playground !</b><br/>L&apos;&eacute;quipe Playground</font>
																				</td>
																			</tr>
																			<tr height="20">
																				<td height="20" width="450" style="font-size:0">
																					<img border="0" src="<?php echo $this->url('frontend', array(), array('force_canonical' => true)). 'images/content/email/email8.jpg';?>" alt="" height="20" width="450"/>
																				</td>
																			</tr>
																			<tr height="38">
																				<td height="38" width="450" bgcolor="#F3F3F3">
																					<table width="450" cellpadding="0" cellspacing="0" border="0">
																						<tr height="38">
																							<td height="38" width="124" style="font-size:0">&nbsp;</td>
																							<td height="38" width="208" style="font-size:0">
																								<table width="208" cellpadding="0" cellspacing="0" border="0">
																									<tr height="38">
																										<td height="38" width="34" style="font-size:0">
																											<img border="0" src="<?php echo $this->url('frontend', array(), array('force_canonical' => true)). 'images/content/email/email9.jpg';?>" alt="" height="38" width="34"/>
																										</td>
																										<td height="38" width="174" style="font-size:14px">
																											<a href="http://facebook.com/playground/" style="color:#3B5A99;"><font face="Arial" color="#3B5A99">Suivez-nous sur Facebook</font></a>
																										</td>
																									</tr>
																								</table>
																							</td>
																							<td height="38" width="118" style="font-size:0">&nbsp;</td>
																						</tr>
																					</table>
																				</td>
																			</tr>
																		</table>
																	</td>
																</tr>
															</table>
														</td>
														<td height="487" width="15" style="font-size:0"><img border="0" src="<?php echo $this->url('frontend', array(), array('force_canonical' => true)). 'images/content/email/email5.jpg';?>" alt="" height="487" width="15"/></td>
													</table>
												</td>
											</tr>
										</table>
									</td>
									<td height="589" width="18" style="font-size:0" valign="top">
										<img border="0" src="<?php echo $this->url('frontend', array(), array('force_canonical' => true)). 'images/content/email/email2.jpg';?>" alt="" height="589" width="18"/>
									</td>	
								</tr>	
							</table>
					</td>					
				</tr>	
			</table>		
		</td>
	</tr>
</table>
		
</body>
</html>
